import {
  BROWSER_043_COMPUTER_CAPABILITY_PROFILE,
  COMPUTER_TASK_RUNTIME_CAPABILITY_PROFILE,
  CURRENT_COMPUTER_USE_CAPABILITY_PROFILE,
  DESKTOP_UI_CAPABILITY_PROFILE,
  DOCUMENT_MODEL_CAPABILITY_PROFILE,
  FILESYSTEM_CAPABILITY_PROFILE,
  LOCAL_COMPUTE_CAPABILITY_PROFILE,
  PROCESS_CAPABILITY_PROFILE,
  REALTIME_MEDIA_GAME_CAPABILITY_PROFILE,
  REMOTE_SESSION_CAPABILITY_PROFILE,
  SYSTEM_DEVICE_CAPABILITY_PROFILE,
  TERMINAL_CAPABILITY_PROFILE,
  type ComputerUseCapabilityProfile,
} from './computerUseCapabilityProfiles.js';

/**
 * Auditable inventory of the component profiles that currently feed the
 * integrated computer-use profile. Keeping this separate from the composition
 * implementation gives tests and tooling a stable place to enumerate source
 * evidence without widening the historical browser profile.
 */
export const CURRENT_COMPUTER_USE_COMPONENT_PROFILES: readonly ComputerUseCapabilityProfile[] = Object.freeze([
  BROWSER_043_COMPUTER_CAPABILITY_PROFILE,
  COMPUTER_TASK_RUNTIME_CAPABILITY_PROFILE,
  FILESYSTEM_CAPABILITY_PROFILE,
  PROCESS_CAPABILITY_PROFILE,
  TERMINAL_CAPABILITY_PROFILE,
  LOCAL_COMPUTE_CAPABILITY_PROFILE,
  DESKTOP_UI_CAPABILITY_PROFILE,
  REMOTE_SESSION_CAPABILITY_PROFILE,
  SYSTEM_DEVICE_CAPABILITY_PROFILE,
  DOCUMENT_MODEL_CAPABILITY_PROFILE,
  REALTIME_MEDIA_GAME_CAPABILITY_PROFILE,
]);

export const CURRENT_COMPUTER_USE_PROFILE_CATALOG = Object.freeze({
  integrated: CURRENT_COMPUTER_USE_CAPABILITY_PROFILE,
  components: CURRENT_COMPUTER_USE_COMPONENT_PROFILES,
});
