import { utf8Bytes, validateStructuredEntityRef } from './documentModelIdentity.js';
import type { CellAddress,CellRange,CodeRange,TextRange } from './documentModelTypes.js';
const MAX_OBSERVATION_LIMIT=1_000_000;
function nonNegativeInt(v:number):boolean{return Number.isSafeInteger(v)&&v>=0}
export function validateTextRange(r:TextRange,textLength?:number):readonly string[]{const e:string[]=[];if(!nonNegativeInt(r.start))e.push('range start must be a non-negative safe integer');if(!Number.isSafeInteger(r.end)||r.end<r.start)e.push('range end must be a safe integer at or after start');if(textLength!==undefined&&r.end>textLength)e.push('range exceeds observed text length');return e}
export function validateCellAddress(a:CellAddress):readonly string[]{const e:string[]=[];if(!nonNegativeInt(a.row))e.push('cell row must be a non-negative safe integer');if(!nonNegativeInt(a.column))e.push('cell column must be a non-negative safe integer');return e}
export function validateCellRange(r:CellRange):readonly string[]{const e=[...validateStructuredEntityRef(r.sheet),...validateCellAddress(r.start),...validateCellAddress(r.end)];if(r.sheet.kind!=='sheet')e.push('cell range target must be a sheet');if(nonNegativeInt(r.start.row)&&nonNegativeInt(r.end.row)&&r.end.row<r.start.row)e.push('cell range end row must be at or after start row');if(nonNegativeInt(r.start.column)&&nonNegativeInt(r.end.column)&&r.end.column<r.start.column)e.push('cell range end column must be at or after start column');return e}
export function validateCodeRange(r:CodeRange):readonly string[]{const e=[...validateStructuredEntityRef(r.buffer)];for(const [n,p] of [['start',r.start],['end',r.end]] as const){if(!nonNegativeInt(p.line))e.push(`code range ${n} line must be a non-negative safe integer`);if(!nonNegativeInt(p.column))e.push(`code range ${n} column must be a non-negative safe integer`)}if(nonNegativeInt(r.start.line)&&nonNegativeInt(r.end.line)&&(r.end.line<r.start.line||(r.end.line===r.start.line&&r.end.column<r.start.column)))e.push('code range end must be at or after start');return e}
export interface ObservationBounds { maxItems:number;maxTextBytes:number }
export type TextExposure='content'|'metadata-only';
export interface TextObservation { range:TextRange;exposure:TextExposure;text?:string;totalUtf8Bytes:number;exposedUtf8Bytes:number;truncated:boolean;omittedUtf8Bytes:number }
export interface BoundedItemsObservation {items:readonly string[];totalItems:number;exposedTextBytes:number;truncated:boolean;omittedItems:number}
export function validateObservationBounds(b:ObservationBounds):readonly string[]{const e:string[]=[];if(!Number.isSafeInteger(b.maxItems)||b.maxItems<1||b.maxItems>MAX_OBSERVATION_LIMIT)e.push('maxItems must be a positive bounded safe integer');if(!Number.isSafeInteger(b.maxTextBytes)||b.maxTextBytes<1||b.maxTextBytes>MAX_OBSERVATION_LIMIT)e.push('maxTextBytes must be a positive bounded safe integer');return e}
function truncateUtf8(v:string,max:number):string{if(utf8Bytes(v)<=max)return v;let l=0,h=v.length;while(l<h){const m=Math.ceil((l+h)/2);if(utf8Bytes(v.slice(0,m))<=max)l=m;else h=m-1}if(l>0){const c=v.charCodeAt(l-1);if(c>=0xd800&&c<=0xdbff)l--}return v.slice(0,l)}
export function observeTextRange(source:string,range:TextRange,bounds:ObservationBounds,exposure:TextExposure='content'):TextObservation{const e=[...validateObservationBounds(bounds),...validateTextRange(range,source.length)];if(e.length)throw new Error(e.join('; '));const selected=source.slice(range.start,range.end),totalUtf8Bytes=utf8Bytes(selected);if(exposure==='metadata-only')return {range,exposure,totalUtf8Bytes,exposedUtf8Bytes:0,truncated:totalUtf8Bytes>0,omittedUtf8Bytes:totalUtf8Bytes};const text=truncateUtf8(selected,bounds.maxTextBytes),exposedUtf8Bytes=utf8Bytes(text);return {range,exposure,text,totalUtf8Bytes,exposedUtf8Bytes,truncated:exposedUtf8Bytes<totalUtf8Bytes,omittedUtf8Bytes:totalUtf8Bytes-exposedUtf8Bytes}}
export function observeBoundedItems<T>(items:readonly T[],bounds:ObservationBounds,project?:(item:T)=>string):BoundedItemsObservation{const e=validateObservationBounds(bounds);if(e.length)throw new Error(e.join('; '));const visible:string[]=[];let exposedTextBytes=0;for(const item of items){if(visible.length>=bounds.maxItems)break;let projected:string;if(project){projected=project(item)}else{if(typeof item!=='string')throw new Error('structured items require an explicit bounded string projection');projected=item}if(typeof projected!=='string')throw new Error('item projection must return a string');const bytes=utf8Bytes(projected);if(bytes>bounds.maxTextBytes-exposedTextBytes)break;visible.push(projected);exposedTextBytes+=bytes}return {items:visible,totalItems:items.length,exposedTextBytes,truncated:visible.length<items.length,omittedItems:items.length-visible.length}}
