import { sameDocumentRef,sameStructuredEntityRef,utf8Bytes,validOpaqueId,validateDocumentRef,validateStructuredEntityRef } from './documentModelIdentity.js';
import type { DocumentRef,StructuredEntityKind,StructuredEntityRef } from './documentModelIdentity.js';
import { validateCellRange,validateCodeRange,validateTextRange } from './documentModelObservation.js';
import type { CellRange,CodeBufferRef,CodeRange,PresentationObjectKind,SpreadsheetScalar,TextFormattingPatch,TextRange } from './documentModelTypes.js';
export const SEMANTIC_EFFECT_CLASSES=['local-reversible-edit','local-destructive-edit','local-persistence','external-publication'] as const;
export type SemanticEffectClass=typeof SEMANTIC_EFFECT_CLASSES[number];
export const SEMANTIC_INTENT_KINDS=['insert-text','replace-text','apply-text-formatting','set-cell-value','set-cell-formula','add-structured-object','remove-structured-object','reorder-structured-object','edit-code-buffer','save-document','export-document','publish-document'] as const;
export type SemanticIntentKind=typeof SEMANTIC_INTENT_KINDS[number];
interface Base{intentId:string;document:DocumentRef;effect:SemanticEffectClass}
export interface InsertTextIntent extends Base{kind:'insert-text';effect:'local-reversible-edit';target:StructuredEntityRef;at:number;text:string}
export interface ReplaceTextIntent extends Base{kind:'replace-text';effect:'local-reversible-edit'|'local-destructive-edit';target:StructuredEntityRef;range:TextRange;text:string}
export interface ApplyTextFormattingIntent extends Base{kind:'apply-text-formatting';effect:'local-reversible-edit';target:StructuredEntityRef;range:TextRange;formatting:TextFormattingPatch}
export interface SetCellValueIntent extends Base{kind:'set-cell-value';effect:'local-reversible-edit'|'local-destructive-edit';target:CellRange;value:SpreadsheetScalar}
export interface SetCellFormulaIntent extends Base{kind:'set-cell-formula';effect:'local-reversible-edit'|'local-destructive-edit';target:CellRange;formula:string}
export interface AddStructuredObjectIntent extends Base{kind:'add-structured-object';effect:'local-reversible-edit';container:StructuredEntityRef;objectKind:StructuredEntityKind|PresentationObjectKind|string;beforeEntityId?:string;properties?:Readonly<Record<string,string|number|boolean|null>>}
export interface RemoveStructuredObjectIntent extends Base{kind:'remove-structured-object';effect:'local-reversible-edit'|'local-destructive-edit';target:StructuredEntityRef}
export interface ReorderStructuredObjectIntent extends Base{kind:'reorder-structured-object';effect:'local-reversible-edit';target:StructuredEntityRef;beforeEntityId?:string}
export interface EditCodeBufferIntent extends Base{kind:'edit-code-buffer';effect:'local-reversible-edit'|'local-destructive-edit';target:CodeBufferRef;range:CodeRange;text:string}
export interface SaveDocumentIntent extends Base{kind:'save-document';effect:'local-persistence'}
export interface ExportDocumentIntent extends Base{kind:'export-document';effect:'local-persistence'|'external-publication';format:string;destination:{kind:'local-artifact';artifactId:string}|{kind:'external-target';targetId:string}}
export interface PublishDocumentIntent extends Base{kind:'publish-document';effect:'external-publication';destinationId:string}
export type SemanticEditIntent=InsertTextIntent|ReplaceTextIntent|ApplyTextFormattingIntent|SetCellValueIntent|SetCellFormulaIntent|AddStructuredObjectIntent|RemoveStructuredObjectIntent|ReorderStructuredObjectIntent|EditCodeBufferIntent|SaveDocumentIntent|ExportDocumentIntent|PublishDocumentIntent;
const MAX_TEXT=1_000_000,MAX_SHORT=4_096,MAX_PROPERTIES=1_024,MAX_PROP_TEXT=16_384,MAX_PROP_TOTAL=1_000_000;
const EFFECTS:Record<SemanticIntentKind,readonly SemanticEffectClass[]>={ 'insert-text':['local-reversible-edit'],'replace-text':['local-reversible-edit','local-destructive-edit'],'apply-text-formatting':['local-reversible-edit'],'set-cell-value':['local-reversible-edit','local-destructive-edit'],'set-cell-formula':['local-reversible-edit','local-destructive-edit'],'add-structured-object':['local-reversible-edit'],'remove-structured-object':['local-reversible-edit','local-destructive-edit'],'reorder-structured-object':['local-reversible-edit'],'edit-code-buffer':['local-reversible-edit','local-destructive-edit'],'save-document':['local-persistence'],'export-document':['local-persistence','external-publication'],'publish-document':['external-publication']};
function text(v:string,label:string,max=MAX_TEXT,empty=true):string[]{const e:string[]=[];if(!empty&&v.length===0)e.push(`${label} must not be empty`);if(utf8Bytes(v)>max)e.push(`${label} exceeds maximum UTF-8 byte length`);return e}
function formatting(v:TextFormattingPatch):string[]{const e:string[]=[];if(v.fontFamily!==undefined)e.push(...text(v.fontFamily,'fontFamily',MAX_SHORT,false));if(v.paragraphStyle!==undefined)e.push(...text(v.paragraphStyle,'paragraphStyle',MAX_SHORT,false));if(v.fontSizePoints!==undefined&&(!Number.isFinite(v.fontSizePoints)||v.fontSizePoints<=0))e.push('fontSizePoints must be a positive finite number');return e}
function properties(v:Readonly<Record<string,string|number|boolean|null>>|undefined):string[]{if(!v)return[];const entries=Object.entries(v),e:string[]=[];if(entries.length>MAX_PROPERTIES)e.push('object properties exceed maximum property count');let total=0;for(const [k,x] of entries){if(!validOpaqueId(k))e.push('object property key must be a bounded identifier');if(typeof x==='string'){const n=utf8Bytes(x);total+=n;if(n>MAX_PROP_TEXT)e.push('object property string exceeds maximum UTF-8 byte length')}else if(typeof x==='number'&&!Number.isFinite(x))e.push('object property numbers must be finite')}if(total>MAX_PROP_TOTAL)e.push('object property strings exceed total UTF-8 byte limit');return e}
function allowed(kind:unknown,effect:unknown):string[]{if(typeof kind!=='string'||!SEMANTIC_INTENT_KINDS.includes(kind as SemanticIntentKind))return ['intent kind is unsupported'];if(typeof effect!=='string'||!SEMANTIC_EFFECT_CLASSES.includes(effect as SemanticEffectClass))return ['intent effect is unsupported'];return EFFECTS[kind as SemanticIntentKind].includes(effect as SemanticEffectClass)?[]:[`effect is not allowed for ${kind}`]}
export function validateIntent(i:SemanticEditIntent):readonly string[]{const raw=i as unknown as {kind?:unknown;effect?:unknown;document?:DocumentRef;intentId?:string};const ae=allowed(raw.kind,raw.effect);if(ae.length)return ae;if(!raw.document)return ['intent document is required'];const e=[...validateDocumentRef(raw.document)];if(typeof raw.intentId!=='string'||!validOpaqueId(raw.intentId))e.push('intentId must be a bounded opaque identifier');const target=(t:StructuredEntityRef)=>{e.push(...validateStructuredEntityRef(t));if(!sameDocumentRef(t.document,raw.document!))e.push('target document does not match intent document identity')};switch(i.kind){case'insert-text':target(i.target);if(!Number.isSafeInteger(i.at)||i.at<0)e.push('insert offset must be a non-negative safe integer');e.push(...text(i.text,'text'));break;case'replace-text':target(i.target);e.push(...validateTextRange(i.range),...text(i.text,'text'));break;case'apply-text-formatting':target(i.target);e.push(...validateTextRange(i.range),...formatting(i.formatting));break;case'set-cell-value':target(i.target.sheet);e.push(...validateCellRange(i.target));if(typeof i.value==='number'&&!Number.isFinite(i.value))e.push('cell numeric value must be finite');if(typeof i.value==='string')e.push(...text(i.value,'cell value'));break;case'set-cell-formula':target(i.target.sheet);e.push(...validateCellRange(i.target),...text(i.formula,'formula',MAX_TEXT,false));break;case'add-structured-object':target(i.container);e.push(...text(i.objectKind,'objectKind',MAX_SHORT,false),...properties(i.properties));if(i.beforeEntityId!==undefined&&!validOpaqueId(i.beforeEntityId))e.push('beforeEntityId must be a bounded opaque identifier');break;case'remove-structured-object':target(i.target);break;case'reorder-structured-object':target(i.target);if(i.beforeEntityId!==undefined&&!validOpaqueId(i.beforeEntityId))e.push('beforeEntityId must be a bounded opaque identifier');break;case'edit-code-buffer':target(i.target);e.push(...validateCodeRange(i.range),...text(i.text,'text'));if(!sameStructuredEntityRef(i.range.buffer,i.target))e.push('code range buffer does not match edit target');break;case'save-document':break;case'export-document':e.push(...text(i.format,'export format',MAX_SHORT,false));if(i.destination.kind==='local-artifact'){if(!validOpaqueId(i.destination.artifactId))e.push('artifactId must be a bounded opaque identifier');if(i.effect!=='local-persistence')e.push('local export must be classified as local-persistence')}else{if(!validOpaqueId(i.destination.targetId))e.push('targetId must be a bounded opaque identifier');if(i.effect!=='external-publication')e.push('external export must be classified as external-publication')}break;case'publish-document':if(!validOpaqueId(i.destinationId))e.push('destinationId must be a bounded opaque identifier');break}return e}
export function classifyIntentEffect(i:SemanticEditIntent):SemanticEffectClass{const e=validateIntent(i);if(e.length)throw new Error(`invalid semantic intent: ${e.join('; ')}`);return i.effect}
