import { checkDocumentFreshness,checkEntityFreshness,sameDocumentRef,sameStructuredEntityRef } from './documentModelIdentity.js';
import type { DocumentIdentityState,DocumentRef,FreshnessFailure,FreshnessResult,StructuredEntityRef } from './documentModelIdentity.js';
import type { CellAddress,SpreadsheetCellInput,SpreadsheetCellState,TextRange } from './documentModelTypes.js';
import type { TextObservation } from './documentModelObservation.js';
export type VerificationTarget={kind:'document';document:DocumentRef}|{kind:'entity';entity:StructuredEntityRef};
export type ModelObservation={kind:'text';target:StructuredEntityRef;revision:number;observation:TextObservation}|{kind:'cells';target:StructuredEntityRef;revision:number;cells:readonly SpreadsheetCellState[];truncated:boolean}|{kind:'entity-order';target:StructuredEntityRef;revision:number;entityIds:readonly string[];truncated:boolean}|{kind:'saved-state';target:DocumentRef;revision:number;savedRevision:number};
export type VerificationExpectation={kind:'text-equals';target:StructuredEntityRef;range:TextRange;expected:string}|{kind:'cell-input-equals';target:StructuredEntityRef;address:CellAddress;expected:SpreadsheetCellInput}|{kind:'entity-order-equals';target:StructuredEntityRef;expectedEntityIds:readonly string[]}|{kind:'saved-revision-at-least';target:DocumentRef;minimumRevision:number};
export interface PostEditVerificationRequest{identity:DocumentIdentityState;beforeRevision:number;expectation:VerificationExpectation;observation:ModelObservation}
export type PostEditVerification={status:'verified';evidence:readonly string[]}|{status:'stale-target';reason:FreshnessFailure;evidence:readonly string[]}|{status:'insufficient-observation';evidence:readonly string[]}|{status:'mismatch';evidence:readonly string[]};
function rev(v:number):boolean{return Number.isSafeInteger(v)&&v>=0}
function input(a:SpreadsheetCellInput,b:SpreadsheetCellInput):boolean{if(a.kind!==b.kind)return false;if(a.kind==='blank'&&b.kind==='blank')return true;if(a.kind==='value'&&b.kind==='value')return Object.is(a.value,b.value);return a.kind==='formula'&&b.kind==='formula'&&a.formula===b.formula}
function address(a:CellAddress,b:CellAddress):boolean{return a.row===b.row&&a.column===b.column}
function range(a:TextRange,b:TextRange):boolean{return a.start===b.start&&a.end===b.end}
function freshness(x:VerificationTarget,s:DocumentIdentityState):FreshnessResult{return x.kind==='document'?checkDocumentFreshness(x.document,s.document):checkEntityFreshness(x.entity,s)}
function expectedTarget(x:VerificationExpectation):VerificationTarget{return x.kind==='saved-revision-at-least'?{kind:'document',document:x.target}:{kind:'entity',entity:x.target}}
function sameTarget(x:VerificationExpectation,o:ModelObservation):boolean{return x.kind==='saved-revision-at-least'?o.kind==='saved-state'&&sameDocumentRef(o.target,x.target):o.kind!=='saved-state'&&sameStructuredEntityRef(o.target,x.target)}
export function verifyPostEdit(r:PostEditVerificationRequest):PostEditVerification{if(!rev(r.beforeRevision)||!rev(r.observation.revision))return{status:'insufficient-observation',evidence:['invalid-model-revision']};if(r.expectation.kind==='saved-revision-at-least'&&(!rev(r.expectation.minimumRevision)||(r.observation.kind==='saved-state'&&!rev(r.observation.savedRevision))))return{status:'insufficient-observation',evidence:['invalid-saved-revision']};const f=freshness(expectedTarget(r.expectation),r.identity);if(!f.fresh)return{status:'stale-target',reason:f.reason,evidence:['semantic-target-stale']};if(r.observation.revision<=r.beforeRevision)return{status:'mismatch',evidence:['model-revision-did-not-advance']};if(!sameTarget(r.expectation,r.observation))return{status:'insufficient-observation',evidence:['observation-target-identity-mismatch']};const e=r.expectation,o=r.observation;if(e.kind==='text-equals'){if(o.kind!=='text')return{status:'insufficient-observation',evidence:['text-observation-missing']};if(o.observation.exposure!=='content'||o.observation.text===undefined||o.observation.truncated)return{status:'insufficient-observation',evidence:['text-observation-not-complete']};if(!range(o.observation.range,e.range))return{status:'insufficient-observation',evidence:['text-range-not-targeted']};return o.observation.text===e.expected?{status:'verified',evidence:['text-model-matches']}:{status:'mismatch',evidence:['text-model-mismatch']}}if(e.kind==='cell-input-equals'){if(o.kind!=='cells')return{status:'insufficient-observation',evidence:['cell-observation-missing']};if(o.truncated)return{status:'insufficient-observation',evidence:['cell-observation-truncated']};const c=o.cells.find(x=>address(x.address,e.address));if(!c)return{status:'insufficient-observation',evidence:['target-cell-not-observed']};return input(c.input,e.expected)?{status:'verified',evidence:['cell-input-model-matches']}:{status:'mismatch',evidence:['cell-input-model-mismatch']}}if(e.kind==='entity-order-equals'){if(o.kind!=='entity-order')return{status:'insufficient-observation',evidence:['entity-order-observation-missing']};if(o.truncated)return{status:'insufficient-observation',evidence:['entity-order-observation-truncated']};const m=o.entityIds.length===e.expectedEntityIds.length&&o.entityIds.every((id,n)=>id===e.expectedEntityIds[n]);return m?{status:'verified',evidence:['entity-order-model-matches']}:{status:'mismatch',evidence:['entity-order-model-mismatch']}}if(o.kind!=='saved-state')return{status:'insufficient-observation',evidence:['saved-state-observation-missing']};return o.savedRevision>=e.minimumRevision?{status:'verified',evidence:['saved-model-revision-confirmed']}:{status:'mismatch',evidence:['saved-model-revision-too-old']}}
