import { sameDocumentRef,sameStructuredEntityRef,utf8Bytes,validOpaqueId,validateDocumentRef,validateStructuredEntityRef } from './documentModelIdentity.js';
import type { DocumentRef,StructuredEntityKind,StructuredEntityRef } from './documentModelIdentity.js';
import { validateCellRange,validateCodeRange,validateTextRange } from './documentModelObservation.js';
import type { CellRange,CodeBufferRef,CodeRange,PresentationObjectKind,SpreadsheetScalar,TextFormattingPatch,TextRange } from './documentModelTypes.js';
export const SEMANTIC_EFFECT_CLASSES=['local-reversible-edit','local-destructive-edit','local-persistence','external-publication'] as const;
export type SemanticEffectClass=typeof SEMANTIC_EFFECT_CLASSES[number];
export const SEMANTIC_INTENT_KINDS=['insert-text','replace-text','apply-text-formatting','set-cell-value','set-cell-formula','add-structured-object','remove-structured-object','reorder-structured-object','edit-code-buffer','save-document','export-document','publish-document'] as const;
export type SemanticIntentKind=typeof SEMANTIC_INTENT_KINDS[number];
interface Base{intentId:string;document:DocumentRef;effect:SemanticEffectClass}
export interface InsertTextIntent extends Base{kind:'insert-text';effect:'local-reversible-edit';target:StructuredEntityRef;at:number;text:string}
export interface ReplaceTextIntent extends Base{kind:'replace-text';effect:'local-reversible-edit'|'local-destructive-edit';target:StructuredEntityRef;range:TextRange;text:string}
export interface ApplyTextFormattingIntent extends Base{kind:'apply-text-formatting';effect:'local-reversible-edit';target:StructuredEntityRef;range:TextRange;formatting:TextFormattingPatch}
export interface SetCellValueIntent extends Base{kind:'set-cell-value';effect:'local-reversible-edit'|'local-destructive-edit';target:CellRange;value:SpreadsheetScalar}
export interface SetCellFormulaIntent extends Base{kind:'set-cell-formula';effect:'local-reversible-edit'|'local-destructive-edit';target:CellRange;formula:string}
export interface AddStructuredObjectIntent extends Base{kind:'add-structured-object';effect:'local-reversible-edit';container:StructuredEntityRef;objectKind:StructuredEntityKind|PresentationObjectKind|string;beforeEntityId?:string;properties?:Readonly<Record<string,string|number|boolean|null>>}
export interface RemoveStructuredObjectIntent extends Base{kind:'remove-structured-object';effect:'local-reversible-edit'|'local-destructive-edit';target:StructuredEntityRef}
export interface ReorderStructuredObjectIntent extends Base{kind:'reorder-structured-object';effect:'local-reversible-edit';target:StructuredEntityRef;beforeEntityId?:string}
export interface EditCodeBufferIntent extends Base{kind:'edit-code-buffer';effect:'local-reversible-edit'|'local-destructive-edit';target:CodeBufferRef;range:CodeRange;text:string}
export interface SaveDocumentIntent extends Base{kind:'save-document';effect:'local-persistence'}
export interface ExportDocumentIntent extends Base{kind:'export-document';effect:'local-persistence'|'external-publication';format:string;destination:{kind:'local-artifact';artifactId:string}|{kind:'external-target';targetId:string}}
export interface PublishDocumentIntent extends Base{kind:'publish-document';effect:'external-publication';destinationId:string}
export type SemanticEditIntent=InsertTextIntent|ReplaceTextIntent|ApplyTextFormattingIntent|SetCellValueIntent|SetCellFormulaIntent|AddStructuredObjectIntent|RemoveStructuredObjectIntent|ReorderStructuredObjectIntent|EditCodeBufferIntent|SaveDocumentIntent|ExportDocumentIntent|PublishDocumentIntent;
const MAX_TEXT=1_000_000,MAX_SHORT=4_096,MAX_PROPERTIES=1_024,MAX_PROP_TEXT=16_384,MAX_PROP_TOTAL=1_000_000;
const EFFECTS:Record<SemanticIntentKind,readonly SemanticEffectClass[]>={ 'insert-text':['local-reversible-edit'],'replace-text':['local-reversible-edit','local-destructive-edit'],'apply-text-formatting':['local-reversible-edit'],'set-cell-value':['local-reversible-edit','local-destructive-edit'],'set-cell-formula':['local-reversible-edit','local-destructive-edit'],'add-structured-object':['local-reversible-edit'],'remove-structured-object':['local-reversible-edit','local-destructive-edit'],'reorder-structured-object':['local-reversible-edit'],'edit-code-buffer':['local-reversible-edit','local-destructive-edit'],'save-document':['local-persistence'],'export-document':['local-persistence','external-publication'],'publish-document':['external-publication']};
type RecordValue=Record<string,unknown>;
function record(v:unknown):v is RecordValue{return typeof v==='object'&&v!==null&&!Array.isArray(v)}
function text(v:string,label:string,max=MAX_TEXT,empty=true):string[]{const e:string[]=[];if(!empty&&v.length===0)e.push(`${label} must not be empty`);if(utf8Bytes(v)>max)e.push(`${label} exceeds maximum UTF-8 byte length`);return e}
function allowed(kind:unknown,effect:unknown):string[]{if(typeof kind!=='string'||!SEMANTIC_INTENT_KINDS.includes(kind as SemanticIntentKind))return ['intent kind is unsupported'];if(typeof effect!=='string'||!SEMANTIC_EFFECT_CLASSES.includes(effect as SemanticEffectClass))return ['intent effect is unsupported'];return EFFECTS[kind as SemanticIntentKind].includes(effect as SemanticEffectClass)?[]:[`effect is not allowed for ${kind}`]}
function documentShape(v:unknown,e:string[],label='intent document'):DocumentRef|undefined{if(!record(v)){e.push(`${label} must be an object`);return}let safe=true;if(typeof v.documentId!=='string'){e.push(`${label}.documentId must be a string`);safe=false}if(typeof v.generation!=='number'){e.push(`${label}.generation must be a number`);safe=false}if(typeof v.kind!=='string'){e.push(`${label}.kind must be a string`);safe=false}if(!safe)return;const d=v as unknown as DocumentRef;e.push(...validateDocumentRef(d));return d}
function entityShape(v:unknown,e:string[],label:string):StructuredEntityRef|undefined{if(!record(v)){e.push(`${label} must be an object`);return}const d=documentShape(v.document,e,`${label}.document`);let safe=!!d;if(typeof v.kind!=='string'){e.push(`${label}.kind must be a string`);safe=false}if(typeof v.entityId!=='string'){e.push(`${label}.entityId must be a string`);safe=false}if(typeof v.generation!=='number'){e.push(`${label}.generation must be a number`);safe=false}if(v.parentEntityId!==undefined&&typeof v.parentEntityId!=='string'){e.push(`${label}.parentEntityId must be a string when provided`);safe=false}if(!safe)return;const ref=v as unknown as StructuredEntityRef;e.push(...validateStructuredEntityRef(ref));return ref}
function pointShape(v:unknown,e:string[],label:string):v is {line:number;column:number}{if(!record(v)){e.push(`${label} must be an object`);return false}let safe=true;if(typeof v.line!=='number'){e.push(`${label}.line must be a number`);safe=false}if(typeof v.column!=='number'){e.push(`${label}.column must be a number`);safe=false}return safe}
function textRangeShape(v:unknown,e:string[],label='range'):TextRange|undefined{if(!record(v)){e.push(`${label} must be an object`);return}if(typeof v.start!=='number'||typeof v.end!=='number'){if(typeof v.start!=='number')e.push(`${label}.start must be a number`);if(typeof v.end!=='number')e.push(`${label}.end must be a number`);return}const r=v as unknown as TextRange;e.push(...validateTextRange(r));return r}
function cellAddressShape(v:unknown,e:string[],label:string):boolean{if(!record(v)){e.push(`${label} must be an object`);return false}let safe=true;if(typeof v.row!=='number'){e.push(`${label}.row must be a number`);safe=false}if(typeof v.column!=='number'){e.push(`${label}.column must be a number`);safe=false}return safe}
function cellRangeShape(v:unknown,e:string[],label='target'):CellRange|undefined{if(!record(v)){e.push(`${label} must be an object`);return}const sheet=entityShape(v.sheet,e,`${label}.sheet`);const start=cellAddressShape(v.start,e,`${label}.start`),end=cellAddressShape(v.end,e,`${label}.end`);if(!sheet||!start||!end)return;const r=v as unknown as CellRange;e.push(...validateCellRange(r));return r}
function codeRangeShape(v:unknown,e:string[]):CodeRange|undefined{if(!record(v)){e.push('range must be an object');return}const buffer=entityShape(v.buffer,e,'range.buffer');const start=pointShape(v.start,e,'range.start'),end=pointShape(v.end,e,'range.end');if(!buffer||!start||!end)return;const r=v as unknown as CodeRange;e.push(...validateCodeRange(r));return r}
function formattingShape(v:unknown,e:string[]):TextFormattingPatch|undefined{if(!record(v)){e.push('formatting must be an object');return}let safe=true;for(const k of ['bold','italic','underline','strike'] as const){if(v[k]!==undefined&&typeof v[k]!=='boolean'){e.push(`formatting.${k} must be a boolean when provided`);safe=false}}for(const k of ['fontFamily','paragraphStyle'] as const){if(v[k]!==undefined&&typeof v[k]!=='string'){e.push(`formatting.${k} must be a string when provided`);safe=false}}if(v.fontSizePoints!==undefined&&typeof v.fontSizePoints!=='number'){e.push('formatting.fontSizePoints must be a number when provided');safe=false}if(!safe)return;const f=v as unknown as TextFormattingPatch;if(f.fontFamily!==undefined)e.push(...text(f.fontFamily,'fontFamily',MAX_SHORT,false));if(f.paragraphStyle!==undefined)e.push(...text(f.paragraphStyle,'paragraphStyle',MAX_SHORT,false));if(f.fontSizePoints!==undefined&&(!Number.isFinite(f.fontSizePoints)||f.fontSizePoints<=0))e.push('fontSizePoints must be a positive finite number');return f}
function propertiesShape(v:unknown,e:string[]):Readonly<Record<string,string|number|boolean|null>>|undefined{if(v===undefined)return undefined;if(!record(v)){e.push('properties must be an object when provided');return}const entries=Object.entries(v);if(entries.length>MAX_PROPERTIES)e.push('object properties exceed maximum property count');let total=0,safe=true;for(const [k,x] of entries){if(!validOpaqueId(k))e.push('object property key must be a bounded identifier');if(x!==null&&!['string','number','boolean'].includes(typeof x)){e.push(`object property ${k} must be a string, number, boolean, or null`);safe=false;continue}if(typeof x==='string'){const n=utf8Bytes(x);total+=n;if(n>MAX_PROP_TEXT)e.push('object property string exceeds maximum UTF-8 byte length')}else if(typeof x==='number'&&!Number.isFinite(x))e.push('object property numbers must be finite')}if(total>MAX_PROP_TOTAL)e.push('object property strings exceed total UTF-8 byte limit');return safe?v as Readonly<Record<string,string|number|boolean|null>>:undefined}
function requireString(v:unknown,e:string[],label:string,empty=true,max=MAX_TEXT):v is string{if(typeof v!=='string'){e.push(`${label} must be a string`);return false}e.push(...text(v,label,max,empty));return true}
function targetDocument(ref:StructuredEntityRef|undefined,doc:DocumentRef|undefined,e:string[]):void{if(ref&&doc&&!sameDocumentRef(ref.document,doc))e.push('target document does not match intent document identity')}
export function validateIntent(input:unknown):readonly string[]{const e:string[]=[];if(!record(input))return ['intent must be an object'];const ae=allowed(input.kind,input.effect);e.push(...ae);const doc=documentShape(input.document,e);if(typeof input.intentId!=='string'||!validOpaqueId(input.intentId))e.push('intentId must be a bounded opaque identifier');if(ae.some(x=>x==='intent kind is unsupported'))return e;const kind=input.kind as SemanticIntentKind;switch(kind){
case'insert-text':{const t=entityShape(input.target,e,'target');targetDocument(t,doc,e);if(typeof input.at!=='number')e.push('at must be a number');else if(!Number.isSafeInteger(input.at)||input.at<0)e.push('insert offset must be a non-negative safe integer');requireString(input.text,e,'text');break}
case'replace-text':{const t=entityShape(input.target,e,'target');targetDocument(t,doc,e);textRangeShape(input.range,e);requireString(input.text,e,'text');break}
case'apply-text-formatting':{const t=entityShape(input.target,e,'target');targetDocument(t,doc,e);textRangeShape(input.range,e);formattingShape(input.formatting,e);break}
case'set-cell-value':{const r=cellRangeShape(input.target,e);targetDocument(r?.sheet,doc,e);const v=input.value;if(v!==null&&!['string','number','boolean'].includes(typeof v))e.push('cell value must be a string, number, boolean, or null');else if(typeof v==='number'&&!Number.isFinite(v))e.push('cell numeric value must be finite');else if(typeof v==='string')e.push(...text(v,'cell value'));break}
case'set-cell-formula':{const r=cellRangeShape(input.target,e);targetDocument(r?.sheet,doc,e);requireString(input.formula,e,'formula',false);break}
case'add-structured-object':{const t=entityShape(input.container,e,'container');targetDocument(t,doc,e);requireString(input.objectKind,e,'objectKind',false,MAX_SHORT);if(input.beforeEntityId!==undefined&&(typeof input.beforeEntityId!=='string'||!validOpaqueId(input.beforeEntityId)))e.push('beforeEntityId must be a bounded opaque identifier');propertiesShape(input.properties,e);break}
case'remove-structured-object':{const t=entityShape(input.target,e,'target');targetDocument(t,doc,e);break}
case'reorder-structured-object':{const t=entityShape(input.target,e,'target');targetDocument(t,doc,e);if(input.beforeEntityId!==undefined&&(typeof input.beforeEntityId!=='string'||!validOpaqueId(input.beforeEntityId)))e.push('beforeEntityId must be a bounded opaque identifier');break}
case'edit-code-buffer':{const t=entityShape(input.target,e,'target');targetDocument(t,doc,e);if(t&&t.kind!=='code-buffer')e.push('edit target must be a code buffer');const r=codeRangeShape(input.range,e);requireString(input.text,e,'text');if(t&&r&&!sameStructuredEntityRef(r.buffer,t))e.push('code range buffer does not match edit target');break}
case'save-document':break;
case'export-document':{requireString(input.format,e,'export format',false,MAX_SHORT);if(!record(input.destination)){e.push('destination must be an object');break}if(input.destination.kind==='local-artifact'){if(typeof input.destination.artifactId!=='string'||!validOpaqueId(input.destination.artifactId))e.push('artifactId must be a bounded opaque identifier');if(input.effect!=='local-persistence')e.push('local export must be classified as local-persistence')}else if(input.destination.kind==='external-target'){if(typeof input.destination.targetId!=='string'||!validOpaqueId(input.destination.targetId))e.push('targetId must be a bounded opaque identifier');if(input.effect!=='external-publication')e.push('external export must be classified as external-publication')}else e.push('export destination kind is unsupported');break}
case'publish-document':{if(typeof input.destinationId!=='string'||!validOpaqueId(input.destinationId))e.push('destinationId must be a bounded opaque identifier');break}
}return e}
export function classifyIntentEffect(i:SemanticEditIntent):SemanticEffectClass{const e=validateIntent(i);if(e.length)throw new Error(`invalid semantic intent: ${e.join('; ')}`);return i.effect}
