import { RealtimeInputDispatchError, RealtimeSurfaceError, type RealtimeSurfaceLease, type RealtimeTemporalObservation, type RealtimeTemporalObservationRequest, type RealtimeInput } from './realtimeSurfaceTypes.js';
import { RealtimeSurfaceRuntime, validateRealtimeInput, validateRealtimeVisualBounds } from './realtimeSurfaceCore.js';

const MAX_CAL_CANDIDATES = 16, MAX_CAL_INPUTS = 4, MAX_CAL_SAMPLES = 8, MAX_CAL_MS = 250, MAX_CAL_ACTIONS = 64;
function positiveInt(v: number, max: number) { return Number.isSafeInteger(v) && v >= 1 && v <= max; }
function opaque(v: string, field: string) { if (!v || /[\r\n\0]/.test(v) || new TextEncoder().encode(v).byteLength > 256) throw new RealtimeSurfaceError('invalid-identity', `${field} must be a bounded opaque identifier`); }

export interface RealtimeCalibrationCandidate { id: string; inputs: readonly RealtimeInput[]; probeDurationMs: number; keyboardSafety: 'not-applicable' | 'ordinary' | 'potentially-consequential' }
export interface RealtimeCalibrationSafetyAttestation { purpose: 'bounded-control-calibration'; consequentialCandidateIds: readonly string[] }
export interface RealtimeCalibrationPlan { candidates: readonly RealtimeCalibrationCandidate[]; samplesPerPhase: number; visual: Omit<RealtimeTemporalObservationRequest,'maxSamples'>; maxActions: number; safetyAttestation?: RealtimeCalibrationSafetyAttestation }
export interface RealtimeCalibrationCandidateResult { id:string; status:'observed'|'rejected'; reason?:string; baseline?:RealtimeTemporalObservation; after?:RealtimeTemporalObservation }
export interface RealtimeCalibrationResult { candidates: readonly RealtimeCalibrationCandidateResult[]; actionsDispatched:number; truncated:boolean }
function calibrationOk(p: RealtimeCalibrationPlan) { if (!positiveInt(p.candidates.length,MAX_CAL_CANDIDATES)||!positiveInt(p.samplesPerPhase,MAX_CAL_SAMPLES)||!positiveInt(p.maxActions,MAX_CAL_ACTIONS)) throw new RealtimeSurfaceError('calibration-bound','calibration plan exceeds bounds'); const ids=new Set<string>(); for (const c of p.candidates) { opaque(c.id,'candidate id'); if (ids.has(c.id)||!positiveInt(c.inputs.length,MAX_CAL_INPUTS)||!Number.isSafeInteger(c.probeDurationMs)||c.probeDurationMs<0||c.probeDurationMs>MAX_CAL_MS) throw new RealtimeSurfaceError('calibration-bound','candidate exceeds bounds'); ids.add(c.id); c.inputs.forEach(validateRealtimeInput); const k=c.inputs.some(i=>i.kind==='keyboard'); if (k && c.keyboardSafety==='not-applicable') throw new RealtimeSurfaceError('calibration-safety','keyboard candidate must identify safety scope'); if (!k && c.keyboardSafety!=='not-applicable') throw new RealtimeSurfaceError('calibration-safety','non-keyboard candidate must use not-applicable'); } }
export async function runBoundedRealtimeCalibration(runtime:RealtimeSurfaceRuntime,lease:RealtimeSurfaceLease,plan:RealtimeCalibrationPlan,options:{sleep?:(ms:number)=>Promise<void>}={}):Promise<RealtimeCalibrationResult>{ calibrationOk(plan); validateRealtimeVisualBounds(plan.visual.bounds,plan.visual.limits); const sleep=options.sleep??(async ms=>{if(ms>0)await new Promise(r=>setTimeout(r,ms));}); const results:RealtimeCalibrationCandidateResult[]=[]; let actions=0,truncated=false; for(const c of plan.candidates){ const baseline=await runtime.observeVisual(lease,{...plan.visual,maxSamples:plan.samplesPerPhase}); truncated ||= baseline.truncated; if(c.inputs.some(i=>i.kind==='keyboard') && !(plan.safetyAttestation?.purpose==='bounded-control-calibration' && plan.safetyAttestation.consequentialCandidateIds.includes(c.id))){results.push({id:c.id,status:'rejected',reason:'safety-attestation-required',baseline});continue;} if(actions+c.inputs.length>plan.maxActions){results.push({id:c.id,status:'rejected',reason:'action-budget-exhausted',baseline});truncated=true;continue;} let notDispatched=false,terminate=false; for(const i of c.inputs){ try{const d=await runtime.dispatchInput(lease,i); if(d.dispatch==='dispatched-once')actions++; else if(d.dispatch==='unknown'){results.push({id:c.id,status:'rejected',reason:'input-dispatch-unknown',baseline});truncated=true;terminate=true;break;} else {notDispatched=true;break;}}catch(e){if(e instanceof RealtimeInputDispatchError&&e.dispatch==='unknown'){results.push({id:c.id,status:'rejected',reason:'input-dispatch-unknown',baseline});truncated=true;terminate=true;break;}throw e;}} if(terminate)break; if(notDispatched){results.push({id:c.id,status:'rejected',reason:'input-not-dispatched',baseline});continue;} await sleep(c.probeDurationMs); const after=await runtime.observeVisual(lease,{...plan.visual,maxSamples:plan.samplesPerPhase}); truncated ||= after.truncated; results.push({id:c.id,status:'observed',baseline,after}); } return {candidates:results,actionsDispatched:actions,truncated}; }
