import { sameComputerSurface, type ComputerSurfaceRef } from './environmentAdapter.js';
import {
  RealtimeInputDispatchError, RealtimeSurfaceError,
  type RealtimeFullscreenState, type RealtimeInput, type RealtimeInputDispatchResult, type RealtimeInputOwnershipState, type RealtimeMediaCommand, type RealtimeMediaControlResult, type RealtimeMediaState, type RealtimePlaybackState, type RealtimeSurfaceAdapter, type RealtimeSurfaceDescriptor, type RealtimeSurfaceLease, type RealtimeSurfaceState, type RealtimeTemporalObservation, type RealtimeTemporalObservationRequest, type RealtimeTemporalSample, type RealtimeVisualBounds, type RealtimeVisualCaptureLimits,
} from './realtimeSurfaceTypes.js';

const MAX_TEMPORAL_SAMPLES = 120, MAX_CAPTURE_PIXELS = 4_194_304, MAX_CAPTURE_BYTES = 8 * 1024 * 1024;
const MAX_OBSERVATION_PIXELS = 16_777_216, MAX_OBSERVATION_BYTES = 32 * 1024 * 1024;
const MAX_ABS_COORD = 1_000_000, MAX_REL_DELTA = 32_768, MAX_WHEEL_DELTA = 100_000;
const PLAYBACK: readonly RealtimePlaybackState[] = ['playing', 'paused', 'stopped', 'buffering', 'ended', 'unknown'];
function positiveInt(v: number, max: number) { return Number.isSafeInteger(v) && v >= 1 && v <= max; }
function generation(v: number) { return Number.isSafeInteger(v) && v >= 0; }
function opaque(v: string, field: string) { if (!v || /[\r\n\0]/.test(v) || new TextEncoder().encode(v).byteLength > 256) throw new RealtimeSurfaceError('invalid-identity', `${field} must be a bounded opaque identifier`); }
function own(d: RealtimeSurfaceDescriptor, s: ComputerSurfaceRef) { if (s.adapterId !== d.adapterId || s.environment !== d.environment) throw new RealtimeSurfaceError('adapter-ownership-lost', 'surface is not owned by this adapter/environment'); }
export function validateRealtimeVisualBounds(b: RealtimeVisualBounds | undefined, l: RealtimeVisualCaptureLimits) { if (!positiveInt(l.maxPixels, MAX_CAPTURE_PIXELS) || !positiveInt(l.maxBytes, MAX_CAPTURE_BYTES)) throw new RealtimeSurfaceError('invalid-visual-bound', 'capture limits exceed hard bounds'); if (b && (![b.x,b.y,b.width,b.height].every(Number.isFinite) || b.width <= 0 || b.height <= 0 || Math.ceil(b.width) * Math.ceil(b.height) > l.maxPixels)) throw new RealtimeSurfaceError('visual-bound-exceeded', 'requested visual region exceeds bounds'); }
function stateOk(s: RealtimeSurfaceState, d: RealtimeSurfaceDescriptor) { own(d, s.surface); if (!generation(s.surface.generation) || !generation(s.captureGeneration) || !generation(s.relativePointer.generation)) throw new RealtimeSurfaceError('invalid-generation', 'surface/capture generations must be non-negative safe integers'); opaque(s.ownership.inputOwnerId,'inputOwnerId'); opaque(s.ownership.captureOwnerId,'captureOwnerId'); opaque(s.ownership.sessionOwnerId,'sessionOwnerId'); if (s.ownership.rendererOwnerId !== undefined) opaque(s.ownership.rendererOwnerId,'rendererOwnerId'); if (s.ownership.deviceOwnerId !== undefined) opaque(s.ownership.deviceOwnerId,'deviceOwnerId'); if (s.relativePointer.ownerId !== undefined) opaque(s.relativePointer.ownerId,'relativePointer.ownerId'); }
function lost(a: RealtimeInputOwnershipState, b: RealtimeInputOwnershipState) { if (!b.focused) return 'focus-lost'; if (a.inputOwnerId !== b.inputOwnerId) return 'input-ownership-lost'; if (a.captureOwnerId !== b.captureOwnerId) return 'capture-ownership-lost'; if (a.sessionOwnerId !== b.sessionOwnerId) return 'session-ownership-lost'; if (a.rendererOwnerId !== b.rendererOwnerId) return 'renderer-ownership-lost'; if (a.deviceOwnerId !== b.deviceOwnerId) return 'device-ownership-lost'; }
export function validateRealtimeInput(i: RealtimeInput) { if (i.kind === 'keyboard') return opaque(i.key,'key'); if (i.kind === 'pointer') { if (i.action === 'move' && (![i.x,i.y].every(v => typeof v === 'number' && Number.isFinite(v) && Math.abs(v) <= MAX_ABS_COORD))) throw new RealtimeSurfaceError('invalid-input','absolute pointer coordinates exceed practical bounds'); if (i.action !== 'move' && !i.button) throw new RealtimeSurfaceError('invalid-input','pointer button action requires button'); return; } if (i.kind === 'relative-pointer') { if (![i.dx,i.dy].every(v => Number.isFinite(v) && Math.abs(v) <= MAX_REL_DELTA)) throw new RealtimeSurfaceError('invalid-input','relative pointer delta exceeds practical bounds'); return; } if (i.kind === 'wheel') { if (![i.deltaX,i.deltaY].every(v => Number.isFinite(v) && Math.abs(v) <= MAX_WHEEL_DELTA)) throw new RealtimeSurfaceError('invalid-input','wheel delta exceeds practical bounds'); return; } opaque(i.control,'controller control'); if (!Number.isFinite(i.value) || i.value < -1 || i.value > 1) throw new RealtimeSurfaceError('invalid-input','controller value must be within [-1,1]'); }
function mediaCopy(s: RealtimeMediaState, l: RealtimeSurfaceLease, c: NonNullable<RealtimeSurfaceDescriptor['media']>): RealtimeMediaState { if (!sameComputerSurface(s.surface,l.surface)) throw new RealtimeSurfaceError('stale-surface','media state belongs to stale surface'); if (!PLAYBACK.includes(s.playback)) throw new RealtimeSurfaceError('invalid-media-state','playback state is unsupported'); if (!s.fullscreen || typeof s.fullscreen.active !== 'boolean') throw new RealtimeSurfaceError('invalid-media-state','fullscreen.active must be boolean'); if (s.fullscreen.ownerId !== undefined) opaque(s.fullscreen.ownerId,'fullscreen.ownerId'); if (s.positionMs !== undefined && (!Number.isFinite(s.positionMs) || s.positionMs < 0)) throw new RealtimeSurfaceError('invalid-media-state','invalid positionMs'); if (s.durationMs !== undefined && (!Number.isFinite(s.durationMs) || s.durationMs < 0)) throw new RealtimeSurfaceError('invalid-media-state','invalid durationMs'); if (s.volume !== undefined && (!Number.isFinite(s.volume) || s.volume < 0 || s.volume > 1)) throw new RealtimeSurfaceError('invalid-media-state','invalid volume'); if (s.muted !== undefined && typeof s.muted !== 'boolean') throw new RealtimeSurfaceError('invalid-media-state','muted must be boolean'); const r: RealtimeMediaState = { surface: {...s.surface}, playback: s.playback, fullscreen: {...s.fullscreen} }; if (c.observePosition && s.positionMs !== undefined) r.positionMs=s.positionMs; if (c.observeDuration && s.durationMs !== undefined) r.durationMs=s.durationMs; if (s.volume !== undefined) r.volume=s.volume; if (s.muted !== undefined) r.muted=s.muted; return r; }

export class RealtimeSurfaceRuntime {
  constructor(readonly adapter: RealtimeSurfaceAdapter) {}
  async acquire(surface: ComputerSurfaceRef): Promise<RealtimeSurfaceLease> { own(this.adapter.descriptor,surface); const s=await this.adapter.inspectSurface(surface); stateOk(s,this.adapter.descriptor); if (!sameComputerSurface(surface,s.surface)) throw new RealtimeSurfaceError('stale-surface','requested surface generation is stale'); if (!s.ownership.focused) throw new RealtimeSurfaceError('focus-lost','input lease requires focus'); return { surface:{...s.surface}, captureGeneration:s.captureGeneration, ownership:{...s.ownership}, relativePointerGeneration:s.relativePointer.generation }; }
  private async fresh(l: RealtimeSurfaceLease, input=false) { const s=await this.adapter.inspectSurface(l.surface); stateOk(s,this.adapter.descriptor); if (!sameComputerSurface(s.surface,l.surface)) throw new RealtimeSurfaceError('stale-surface','surface generation changed'); if (s.captureGeneration !== l.captureGeneration) throw new RealtimeSurfaceError('stale-capture','capture generation changed'); if (input) { const e=lost(l.ownership,s.ownership); if (e) throw new RealtimeSurfaceError(e,`realtime input rejected because ${e}`); } return s; }
  async dispatchInput(l: RealtimeSurfaceLease, i: RealtimeInput): Promise<RealtimeInputDispatchResult> { validateRealtimeInput(i); if (!this.adapter.descriptor.supportedInputs.includes(i.kind)) throw new RealtimeSurfaceError('unsupported-input',`adapter does not declare ${i.kind}`); if (i.kind==='controller' && !this.adapter.descriptor.controllerControls?.includes(i.control)) throw new RealtimeSurfaceError('unsupported-input',`adapter does not declare controller control ${i.control}`); const s=await this.fresh(l,true); if (i.kind==='relative-pointer' && (!s.relativePointer.active || s.relativePointer.ownerId!==l.ownership.inputOwnerId || s.relativePointer.generation!==l.relativePointerGeneration)) throw new RealtimeSurfaceError('relative-capture-lost','relative pointer input requires active capture owned by the input lease'); try { const r=await this.adapter.dispatchInput(l.surface,i); if (!r || !['not-dispatched','dispatched-once','unknown'].includes(r.dispatch)) throw new Error('invalid dispatch'); return {dispatch:r.dispatch}; } catch (cause) { throw new RealtimeInputDispatchError('unknown','native input emission state is unknown and must not be retried',cause); } }
  async setRelativePointerCapture(l: RealtimeSurfaceLease, active: boolean): Promise<RealtimeSurfaceLease> { if (!this.adapter.descriptor.supportedInputs.includes('relative-pointer') || !this.adapter.setRelativePointerCapture) throw new RealtimeSurfaceError('unsupported-input','relative pointer unsupported'); const b=await this.fresh(l,true); if (!active && (!b.relativePointer.active || b.relativePointer.ownerId!==l.ownership.inputOwnerId)) throw new RealtimeSurfaceError('relative-capture-lost','capture owned elsewhere'); const a=await this.adapter.setRelativePointerCapture(l.surface,active); stateOk(a,this.adapter.descriptor); if (!sameComputerSurface(a.surface,l.surface) || a.captureGeneration!==l.captureGeneration || lost(l.ownership,a.ownership) || a.relativePointer.active!==active || (active && a.relativePointer.ownerId!==l.ownership.inputOwnerId)) throw new RealtimeSurfaceError('relative-capture-lost','relative pointer transition lost ownership'); return {...l, relativePointerGeneration:a.relativePointer.generation}; }
  async observeVisual(l: RealtimeSurfaceLease, r: RealtimeTemporalObservationRequest): Promise<RealtimeTemporalObservation> { if (!positiveInt(r.maxSamples,MAX_TEMPORAL_SAMPLES)) throw new RealtimeSurfaceError('invalid-sample-bound','maxSamples out of range'); validateRealtimeVisualBounds(r.bounds,r.limits); await this.fresh(l); const samples: RealtimeTemporalSample[]=[]; const ids=new Set<string>(); let ts=-Infinity, seq=-1, drops=0, truncated=false, totalPixels=0, totalBytes=0; for (let order=0; order<r.maxSamples; order++) { const c=await this.adapter.captureVisual({surface:l.surface,captureGeneration:l.captureGeneration,bounds:r.bounds,limits:r.limits}); if (!sameComputerSurface(c.surface,l.surface) || c.captureGeneration!==l.captureGeneration) throw new RealtimeSurfaceError('stale-capture','capture identity changed'); opaque(c.frameId,'frameId'); if (ids.has(c.frameId)) throw new RealtimeSurfaceError('duplicate-frame','frame repeated'); ids.add(c.frameId); if (!Number.isFinite(c.timestampMs) || c.timestampMs<ts || !Number.isSafeInteger(c.sequence) || c.sequence<=seq) throw new RealtimeSurfaceError('temporal-ordering','visual captures must have nondecreasing timestamps and strictly increasing sequence numbers'); if (!Number.isSafeInteger(c.droppedBefore) || c.droppedBefore<0 || !positiveInt(c.width,r.limits.maxPixels) || !positiveInt(c.height,r.limits.maxPixels)) throw new RealtimeSurfaceError('invalid-capture','invalid capture metadata'); if (!(c.data instanceof Uint8Array)) throw new RealtimeSurfaceError('invalid-capture','visual capture data must be Uint8Array'); const bytes=c.data.byteLength, pixels=c.width*c.height; if (c.byteLength!==bytes || bytes>r.limits.maxBytes || pixels>r.limits.maxPixels) throw new RealtimeSurfaceError('visual-bound-exceeded','adapter exceeded bounds or misreported payload size'); totalBytes+=bytes; totalPixels+=pixels; if (totalBytes>MAX_OBSERVATION_BYTES || totalPixels>MAX_OBSERVATION_PIXELS) throw new RealtimeSurfaceError('observation-bound-exceeded','temporal observation exceeded aggregate pixel/byte budget'); ts=c.timestampMs; seq=c.sequence; drops+=c.droppedBefore; truncated ||= c.truncated; samples.push({...c,data:new Uint8Array(c.data),byteLength:bytes,order}); } return {surface:{...l.surface},captureGeneration:l.captureGeneration,samples,droppedSamples:drops,truncated}; }
  async observeMedia(l: RealtimeSurfaceLease) { const c=this.adapter.descriptor.media; if (!c?.observePlayback || !this.adapter.observeMedia) throw new RealtimeSurfaceError('unsupported-media','media observation unsupported'); await this.fresh(l); return mediaCopy(await this.adapter.observeMedia(l.surface),l,c); }
  async controlMedia(l: RealtimeSurfaceLease, cmd: RealtimeMediaCommand): Promise<RealtimeMediaControlResult> { const c=this.adapter.descriptor.media; const ok=cmd.kind==='playback'?c?.setPlayback:cmd.kind==='volume'?c?.setVolume:c?.setMute; if (!ok || !this.adapter.controlMedia) throw new RealtimeSurfaceError('unsupported-media','media control unsupported'); if (cmd.kind==='volume' && (!Number.isFinite(cmd.volume)||cmd.volume<0||cmd.volume>1)) throw new RealtimeSurfaceError('invalid-media-command','invalid volume'); await this.fresh(l,true); const x=await this.adapter.controlMedia(l.surface,cmd); if (x.externalPublicationEffect!=='not-attempted' || !['applied','not-applied','unknown'].includes(x.localMediaEffect)) throw new RealtimeSurfaceError('invalid-media-result','invalid media result'); return {localMediaEffect:x.localMediaEffect,externalPublicationEffect:'not-attempted',...(x.state?{state:mediaCopy(x.state,l,c??{})}:{})}; }
  async setFullscreen(l: RealtimeSurfaceLease, active: boolean) { const c=this.adapter.descriptor.media; if (!c?.fullscreen || !this.adapter.setFullscreen || !this.adapter.observeMedia) throw new RealtimeSurfaceError('unsupported-media','fullscreen unsupported'); await this.fresh(l,true); const b=mediaCopy(await this.adapter.observeMedia(l.surface),l,c); if (!active && b.fullscreen.active && b.fullscreen.ownerId!==l.ownership.inputOwnerId) throw new RealtimeSurfaceError('fullscreen-ownership-lost','fullscreen owned by another actor'); const a=mediaCopy(await this.adapter.setFullscreen(l.surface,active,l.ownership.inputOwnerId),l,c); if (a.fullscreen.active!==active || (active && a.fullscreen.ownerId!==l.ownership.inputOwnerId)) throw new RealtimeSurfaceError('fullscreen-ownership-lost','fullscreen transition lost ownership'); return a; }
}
