// @ts-ignore
import assert from 'node:assert/strict';
// @ts-ignore
import test from 'node:test';
import {checkDocumentFreshness,checkEntityFreshness,classifyIntentEffect,describeReplacement,observeBoundedItems,observeTextRange,validateCellRange,validateCodeRange,validateIntent,verifyPostEdit,type CodeBufferRef,type DocumentIdentityState,type DocumentRef,type SemanticEditIntent,type StructuredEntityRef} from '../src/computer/documentModels.js';
const document:DocumentRef={documentId:'doc-1',generation:3,kind:'word-processing'};
const section:StructuredEntityRef={document,kind:'section',entityId:'section-1',generation:2};
const identity:DocumentIdentityState={document,entities:[{kind:'section',entityId:'section-1',generation:2},{kind:'table',entityId:'table-1',generation:1}]};
test('document identity and generation',()=>{assert.deepEqual(checkDocumentFreshness(document,{...document}),{fresh:true});assert.deepEqual(checkDocumentFreshness(document,{...document,generation:4}),{fresh:false,reason:'document-generation-stale'});assert.deepEqual(checkDocumentFreshness(document,{...document,kind:'presentation'}),{fresh:false,reason:'document-kind-mismatch'});assert.equal(describeReplacement(document,{...document,generation:4},'reopen').reason,'reopen');assert.throws(()=>describeReplacement(document,{...document,generation:3},'reload'))});
test('structured references fail stale',()=>{assert.deepEqual(checkEntityFreshness(section,identity),{fresh:true});assert.deepEqual(checkEntityFreshness({...section,generation:1},identity),{fresh:false,reason:'entity-generation-stale'})});
test('bounded text and privacy',()=>{const o=observeTextRange('prefix αβγ suffix',{start:7,end:10},{maxItems:1,maxTextBytes:4});assert.equal(o.text,'αβ');assert.equal(o.truncated,true);const m=observeTextRange('secret',{start:0,end:6},{maxItems:1,maxTextBytes:32},'metadata-only');assert.equal('text'in m,false);assert.equal(m.exposedUtf8Bytes,0)});
test('bounded items honor count and bytes',()=>{const a=observeBoundedItems(['a','b','c'],{maxItems:2,maxTextBytes:9});assert.deepEqual(a.items,['a','b']);const b=observeBoundedItems([{label:'12345'},{label:'67890'}],{maxItems:10,maxTextBytes:5},x=>x.label);assert.deepEqual(b.items,[{label:'12345'}]);assert.equal(b.exposedTextBytes,5);assert.equal(b.truncated,true)});
test('spreadsheet formulas stay distinct from display',()=>{const d:DocumentRef={documentId:'book',generation:1,kind:'spreadsheet'},s:StructuredEntityRef={document:d,kind:'sheet',entityId:'s',generation:1};const r=verifyPostEdit({identity:{document:d,entities:[{kind:'sheet',entityId:'s',generation:1}]},beforeRevision:1,expectation:{kind:'cell-input-equals',target:s,address:{row:0,column:0},expected:{kind:'formula',formula:'=A1*2'}},observation:{kind:'cells',target:s,revision:2,truncated:false,cells:[{address:{row:0,column:0},input:{kind:'formula',formula:'=A1*2'},displayedValue:'42'}]}});assert.equal(r.status,'verified')});
test('cell and code ranges fail closed',()=>{const d:DocumentRef={documentId:'book',generation:1,kind:'spreadsheet'},s:StructuredEntityRef={document:d,kind:'sheet',entityId:'s',generation:1};assert.equal(validateCellRange({sheet:s,start:{row:-1,column:2},end:{row:0,column:1}}).length>=2,true);assert.ok(validateCellRange({sheet:s,start:{row:2,column:3},end:{row:1,column:2}}).includes('cell range end row must be at or after start row'));const w:DocumentRef={documentId:'w',generation:1,kind:'code-workspace'},b:CodeBufferRef={document:w,kind:'code-buffer',entityId:'b',generation:1};assert.ok(validateCodeRange({buffer:b,start:{line:3,column:8},end:{line:3,column:2}}).includes('code range end must be at or after start'))});
test('intent identity includes document kind and code range full identity',()=>{const bad={...section,document:{...document,kind:'presentation' as const}};const t:SemanticEditIntent={kind:'replace-text',intentId:'i',document,effect:'local-reversible-edit',target:bad,range:{start:0,end:1},text:'x'};assert.ok(validateIntent(t).includes('target document does not match intent document identity'));const w:DocumentRef={documentId:'w',generation:2,kind:'code-workspace'},b:CodeBufferRef={document:w,kind:'code-buffer',entityId:'b',generation:7};const c:SemanticEditIntent={kind:'edit-code-buffer',intentId:'c',document:w,effect:'local-reversible-edit',target:b,range:{buffer:{...b,document:{...w,generation:1}},start:{line:0,column:0},end:{line:0,column:1}},text:'x'};assert.ok(validateIntent(c).includes('code range buffer does not match edit target'))});
test('payloads are bounded and numeric values finite',()=>{const d:DocumentRef={documentId:'book',generation:1,kind:'spreadsheet'},s:StructuredEntityRef={document:d,kind:'sheet',entityId:'s',generation:1};const v:SemanticEditIntent={kind:'set-cell-value',intentId:'v',document:d,effect:'local-reversible-edit',target:{sheet:s,start:{row:0,column:0},end:{row:0,column:0}},value:Infinity};assert.ok(validateIntent(v).includes('cell numeric value must be finite'));const t:SemanticEditIntent={kind:'insert-text',intentId:'t',document,effect:'local-reversible-edit',target:section,at:0,text:'x'.repeat(1_000_001)};assert.ok(validateIntent(t).includes('text exceeds maximum UTF-8 byte length'))});
test('post-edit verification requires model revision',()=>{const r=verifyPostEdit({identity,beforeRevision:2,expectation:{kind:'text-equals',target:section,range:{start:0,end:1},expected:'x'},observation:{kind:'text',target:section,revision:2,observation:observeTextRange('x',{start:0,end:1},{maxItems:1,maxTextBytes:8})}});assert.deepEqual(r,{status:'mismatch',evidence:['model-revision-did-not-advance']})});
test('stale observation identity cannot verify',()=>{const r=verifyPostEdit({identity,beforeRevision:1,expectation:{kind:'text-equals',target:section,range:{start:0,end:1},expected:'x'},observation:{kind:'text',target:{...section,document:{...document,generation:2}},revision:2,observation:observeTextRange('x',{start:0,end:1},{maxItems:1,maxTextBytes:8})}});assert.deepEqual(r,{status:'insufficient-observation',evidence:['observation-target-identity-mismatch']});const s=verifyPostEdit({identity,beforeRevision:1,expectation:{kind:'saved-revision-at-least',target:document,minimumRevision:2},observation:{kind:'saved-state',target:{...document,kind:'presentation'},revision:2,savedRevision:2}});assert.equal(s.status,'insufficient-observation')});
test('truncated observations cannot prove success',()=>{const d:DocumentRef={documentId:'book',generation:1,kind:'spreadsheet'},s:StructuredEntityRef={document:d,kind:'sheet',entityId:'s',generation:1};const r=verifyPostEdit({identity:{document:d,entities:[{kind:'sheet',entityId:'s',generation:1}]},beforeRevision:1,expectation:{kind:'cell-input-equals',target:s,address:{row:0,column:0},expected:{kind:'value',value:42}},observation:{kind:'cells',target:s,revision:2,truncated:true,cells:[{address:{row:0,column:0},input:{kind:'value',value:42}}]}});assert.deepEqual(r,{status:'insufficient-observation',evidence:['cell-observation-truncated']})});
test('local persistence and external publication differ',()=>{const save:SemanticEditIntent={kind:'save-document',intentId:'save',document,effect:'local-persistence'},pub:SemanticEditIntent={kind:'publish-document',intentId:'pub',document,effect:'external-publication',destinationId:'remote'};assert.equal(classifyIntentEffect(save),'local-persistence');assert.equal(classifyIntentEffect(pub),'external-publication');const exp:SemanticEditIntent={kind:'export-document',intentId:'e',document,effect:'local-persistence',format:'pdf',destination:{kind:'local-artifact',artifactId:'a'}};assert.ok(validateIntent({...exp,effect:'external-publication'}).includes('local export must be classified as local-persistence'))});
