import test from 'node:test';
import assert from 'node:assert/strict';
import {RemoteDispatchError,RemoteSessionAdapter,type RemoteCommandInvocation,type RemoteCommandResult,type RemoteDispatchOutcome,type RemoteDisplayFrame,type RemoteEndpointIdentity,type RemoteSessionBackend,type RemoteSessionConnection,type RemoteVisualInput} from '../src/computer/remoteSessionAdapter.js';
import {computerActionMayAutoRetry} from '../src/computer/environmentAdapter.js';
import {ComputerEnvironmentRegistry} from '../src/computer/environmentRegistry.js';

class Gate{private releaseFn!:()=>void;readonly promise=new Promise<void>(r=>this.releaseFn=r);release(){this.releaseFn();}}
class FakeBackend implements RemoteSessionBackend{
 readonly protocol;nextHost='host-a';nextSession='session-1';commandCalls=0;inputCalls=0;disconnectCount=0;disconnectedSessions:string[]=[];invalidNextIdentity=false;metadata=Array.from({length:80},(_,i)=>({key:`k${i}`,value:'value'}));displayFrame:RemoteDisplayFrame={width:2,height:2,format:'synthetic-rgba',bytes:new Uint8Array(16)};commandError:unknown;commandOutcome:RemoteDispatchOutcome<RemoteCommandResult>={dispatch:'dispatched-once',status:'completed',value:{exitCode:0,stdout:'ok'}};inputOutcome:RemoteDispatchOutcome<void>={dispatch:'dispatched-once',status:'completed'};seenCredential:unknown;seenEndpoint?:RemoteEndpointIdentity;lastInput?:RemoteVisualInput;lastInvocation?:RemoteCommandInvocation;commandGate?:Gate;inputGate?:Gate;
 constructor(protocol:'ssh'|'rdp'|'vnc'){this.protocol=protocol;}
 async connect(e:RemoteEndpointIdentity,c?:unknown):Promise<RemoteSessionConnection>{this.seenEndpoint=e;this.seenCredential=c;return{sessionId:this.invalidNextIdentity?'':this.nextSession,remoteHostId:this.nextHost,capabilities:['remote.session.observe','remote.metadata.observe',...(this.protocol==='ssh'?['remote.ssh.execute']:['remote.display.observe','remote.visual.input'])]};}
 async disconnect(c:RemoteSessionConnection){this.disconnectCount++;this.disconnectedSessions.push(c.sessionId)}
 async observeMetadata(){return this.metadata} async captureDisplay(){return this.displayFrame}
 async executeRemoteCommand(_c:RemoteSessionConnection,i:RemoteCommandInvocation){this.commandCalls++;if(this.commandGate)await this.commandGate.promise;this.lastInvocation=i;if(this.commandError)throw this.commandError;return this.commandOutcome}
 async sendVisualInput(_c:RemoteSessionConnection,i:RemoteVisualInput){this.inputCalls++;if(this.inputGate)await this.inputGate.promise;this.lastInput=i;return this.inputOutcome}
}
const endpoint=(p:'ssh'|'rdp'|'vnc'):RemoteEndpointIdentity=>({endpointId:`endpoint-${p}`,protocol:p,host:'explicit.example.test',port:p==='ssh'?22:3389});
const action=(a:RemoteSessionAdapter,authority:any,capability:string,payload:Record<string,unknown>)=>a.act({adapterId:a.adapterId,actionId:'a1',capability,effect:'remote-execution',idempotency:'non-idempotent',payload:{authority,...payload}});

test('connect/disconnect bounded observation and secret privacy',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),credential={kind:'secret-handle' as const,handleId:'vault:test'};await a.connect(credential);const o=await a.observe({adapterId:'r',channel:'terminal',limits:{maxItems:3,maxTextBytes:100}});assert.equal((o.data as any).metadata.length,3);assert.equal(o.truncated,true);assert.equal(JSON.stringify(a.state()).includes('vault:test'),false);assert.notEqual(b.seenCredential,credential);assert.equal(Object.isFrozen(b.seenCredential),true);await a.disconnect();assert.equal(b.disconnectCount,1)});
test('endpoint and secret handles are immutable validated snapshots',async()=>{const original=endpoint('ssh'),b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',original,b);original.endpointId='redirected';original.host='evil.example.test';original.port=2222;original.protocol='rdp';const credential:any={kind:'secret-handle',handleId:'vault:original'};const pending=a.connect(credential);credential.handleId='vault:mutated';const auth=await pending;assert.deepEqual(b.seenEndpoint,{endpointId:'endpoint-ssh',protocol:'ssh',host:'explicit.example.test',port:22});assert.equal(Object.isFrozen(b.seenEndpoint),true);assert.deepEqual(a.state().endpoint,b.seenEndpoint);assert.equal(auth.endpointId,'endpoint-ssh');assert.deepEqual(b.seenCredential,{kind:'secret-handle',handleId:'vault:original'});assert.equal(Object.isFrozen(b.seenCredential),true)});
test('endpoint accessors and exotic shapes reject at construction',()=>{const b=new FakeBackend('ssh'),accessor:any={protocol:'ssh',host:'x',port:22};Object.defineProperty(accessor,'endpointId',{get(){return'endpoint-ssh'},enumerable:true});assert.throws(()=>new RemoteSessionAdapter('r',accessor,b));const exotic:any=Object.create({});Object.assign(exotic,endpoint('ssh'));assert.throws(()=>new RemoteSessionAdapter('r',exotic,b))});
test('reconnect generation and failed replacement cleanup',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),first=await a.connect();b.nextSession='s2';const second=await a.reconnect();assert.equal(second.generation,first.generation+1);b.invalidNextIdentity=true;await assert.rejects(()=>a.reconnect());assert.deepEqual(a.state().authority,second);assert.ok(b.disconnectedSessions.includes(''))});
test('host/session/generation mismatch rejects before dispatch',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),auth=await a.connect();assert.equal((await action(a,{...auth,remoteHostId:'x'},'remote.ssh.execute',{invocation:{command:'true'}})).dispatch,'not-dispatched');const stale=auth;b.nextSession='s2';await a.reconnect();assert.equal((await action(a,stale,'remote.ssh.execute',{invocation:{command:'true'}})).dispatch,'not-dispatched');assert.equal(b.commandCalls,0)});
test('SSH dispatch uncertainty and no retry',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),auth=await a.connect();b.commandError=new RemoteDispatchError('unknown','ssh.transport-unknown');const r=await action(a,auth,'remote.ssh.execute',{invocation:{command:'once'}});assert.equal(r.dispatch,'unknown');assert.equal(computerActionMayAutoRetry({effect:'remote-execution',idempotency:'non-idempotent'} as any,r),false)});
test('SSH argv bounded before dispatch',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),auth=await a.connect();assert.equal((await action(a,auth,'remote.ssh.execute',{invocation:{command:'x',args:['ok',42]}})).dispatch,'not-dispatched');assert.equal((await action(a,auth,'remote.ssh.execute',{invocation:{command:'x',args:['y'.repeat(5000)]}})).dispatch,'not-dispatched');assert.equal(b.commandCalls,0)});
test('registry preserves visual dispatch while verification stays unknown',async()=>{const b=new FakeBackend('rdp'),a=new RemoteSessionAdapter('r',endpoint('rdp'),b),auth=await a.connect(),reg=new ComputerEnvironmentRegistry();reg.register(a);const r=await reg.act({adapterId:'r',actionId:'i',capability:'remote.visual.input',effect:'remote-execution',idempotency:'non-idempotent',payload:{authority:auth,input:{kind:'pointer',x:1,y:1}}});assert.equal(r.status,'unknown');assert.equal(r.dispatch,'dispatched-once')});
test('display observation bounds bytes and dimensions',async()=>{const b=new FakeBackend('rdp'),a=new RemoteSessionAdapter('r',endpoint('rdp'),b);await a.connect();b.displayFrame={width:100,height:100,format:'synthetic-rgba',bytes:new Uint8Array(40000)};const o=await a.observe({adapterId:'r',channel:'visual',limits:{maxTextBytes:10}});assert.equal(o.truncated,true);assert.equal((o.data as any).bytes,undefined);b.displayFrame={width:20000,height:2,format:'synthetic-rgba',bytes:new Uint8Array(1)};await assert.rejects(()=>a.observe({adapterId:'r',channel:'visual'}))});
test('visual input strict bounds reject before backend',async()=>{const b=new FakeBackend('rdp'),a=new RemoteSessionAdapter('r',endpoint('rdp'),b),auth=await a.connect();for(const input of [{kind:'pointer',x:NaN,y:1},{kind:'key',key:'k'.repeat(200)},{kind:'text',text:'x'.repeat(5000)},{kind:'key',key:'A',extra:1}])assert.equal((await action(a,auth,'remote.visual.input',{input})).dispatch,'not-dispatched');assert.equal(b.inputCalls,0)});
test('SSH output bounded with truncation metadata',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),auth=await a.connect();b.commandOutcome={dispatch:'dispatched-once',status:'completed',value:{exitCode:0,stdout:'x'.repeat(70000),stderr:'é'.repeat(40000)}};const d=(await action(a,auth,'remote.ssh.execute',{invocation:{command:'true'}})).details as RemoteCommandResult;assert.ok(new TextEncoder().encode(d.stdout??'').byteLength<=65536);assert.ok(new TextEncoder().encode(d.stderr??'').byteLength<=65536);assert.equal(d.stdoutTruncated,true);assert.equal(d.stderrTruncated,true)});
test('backend evidence sanitized',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),auth=await a.connect();b.commandError=new RemoteDispatchError('unknown','secret prose here');assert.deepEqual((await action(a,auth,'remote.ssh.execute',{invocation:{command:'true'}})).evidence,['remote-backend-evidence-invalid'])});
test('accessor and exotic action payload shapes reject before dispatch',async()=>{const b=new FakeBackend('ssh'),a=new RemoteSessionAdapter('r',endpoint('ssh'),b),auth=await a.connect();const invocation:any={};Object.defineProperty(invocation,'command',{get(){return 'true'},enumerable:true});const r=await action(a,auth,'remote.ssh.execute',{invocation});assert.equal(r.dispatch,'not-dispatched');const exotic=Object.create({});exotic.command='true';assert.equal((await action(a,auth,'remote.ssh.execute',{invocation:exotic})).dispatch,'not-dispatched');assert.equal(b.commandCalls,0)});
test('caller mutation after dispatch start cannot change transport snapshots',async()=>{const sb=new FakeBackend('ssh'),sa=new RemoteSessionAdapter('s',endpoint('ssh'),sb),sauth=await sa.connect();sb.commandGate=new Gate();const args=['safe'];const invocation={command:'printf',args};const sp=action(sa,sauth,'remote.ssh.execute',{invocation});invocation.command='rm';args[0]='mutated';args.push('extra');sb.commandGate.release();await sp;assert.deepEqual(sb.lastInvocation,{command:'printf',args:['safe']});assert.equal(Object.isFrozen(sb.lastInvocation),true);assert.equal(Object.isFrozen(sb.lastInvocation!.args),true);
 const vb=new FakeBackend('rdp'),va=new RemoteSessionAdapter('v',endpoint('rdp'),vb),vauth=await va.connect();vb.inputGate=new Gate();const input:any={kind:'text',text:'safe'};const vp=action(va,vauth,'remote.visual.input',{input});input.text='mutated';input.extra='x';vb.inputGate.release();await vp;assert.deepEqual(vb.lastInput,{kind:'text',text:'safe'});assert.equal(Object.isFrozen(vb.lastInput),true)});
